---
# General Dependencies
general:
  dependencies:
    apt:
      - apt-transport-https # known good with 1.6.6ubuntu0.1 all
      - ca-certificates # known good with 20180409
      - curl # known good with 7.58.0-2ubuntu3.5
      - gnupg-agent # known good with 2.2.4-1ubuntu1.2
      - python3-apt # known good with 1.6.3
      - python3-pip # known good with 9.0.1-2.3~ubuntu1
      - python3-setuptools # known good with 39.0.1-2
      - python-pip
      - software-properties-common # known good with 0.96.24.32.7
    pip:
      - docker
