---
- hosts: ml2
  remote_user: devops
  become: no # Default to non-root user; only execute a task as root when required.
  vars:
    docker_apt_package: docker-ce
    docker_signing_key_url: https://download.docker.com/linux/ubuntu/gpg

    general_dependencies: 
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - python-apt
      - software-properties-common
    
  tasks:
    # General Dependencies
    - name: install general dependencies
      become: true # Must be run as root.
      apt:
        name: "{{ general_dependencies }}"
        update_cache: yes
    
    # General Docker setup
    - name: add Docker's official GPG key
      become: true # Must be run as root.
      apt_key:
        url: "{{ docker_signing_key_url }}"

    - name: add Docker apt repository
      become: true # Must be run as root.
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install Docker CE
      become: true # Must be run as root.
      apt:
        name: "{{ docker_apt_package }}"
        update_cache: yes

    - name: create Docker group to avoid running as root
      become: true # Must be run as root.
      group:
        name: docker
        state: present
    
    - name: add devops user to Docker group
      become: true # Must be run as root.
      user:
        name: devops
        groups:
          - docker
        append: yes

    # Tensorflow Docker Setup
    