################################################################################
# This file consists of three main sections:
#   1. vars - variables used throughout the playbook are defined here. If you want to change packages or version, this is the place to do it.
#   2. tasks - these are the steps that will be executed by the playbook. This is a straightforward, sequential playbook.
#   3. handlers - these steps run only in response to specific events. If the event does not occur, the handler does not run.
################################################################################
---
- hosts: test # Alternatively, 'canary', 'blue'|'green', 'all' according to your deployment strategy and your /etc/ansible/hosts file
  become: yes # All commands must run as root
  strategy: free # Allows all hosts to run to the end of the playbook as fast as they can

  vars_files:
    - secrets.yml

  roles:
    - role: packages # General Dependencies
      tags: [packages]

    # - role: rsync # Rsync Setup
    #   tags: [rsync]
    #   vars:
    #     sync: "{{ secrets.sync }}"

    - role: docker # General Docker setup
      tags: [docker]
      vars:
        users: "{{ secrets.users }}"

    - role: cuda # CUDA Driver Setup
      tags: [cuda]

    - role: nvidia # NVIDIA-Docker Runtime Setup
      tags: [nvidia]

    - role: jupyter # Launch Jupyter Container in Docker
      tags: [jupyter]
      vars:
        volumes: "{{ secrets.volumes }}"
