---
# General Dependencies
- name: install general apt dependencies
  apt:
    name: "{{ general.dependencies.apt }}"
    state: present
    update_cache: yes

- name: install general pip dependencies for Ansible
  pip:
    name: "{{ general.dependencies.pip }}"
    state: present
