---

- name: add Docker apt repository
  apt_repository:
    repo: ppa:ansible/ansible
    state: present

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    update_cache: yes
    state: latest

- name: install general apt dependencies
  apt:
    name: "{{ general.dependencies.apt }}"
    state: present

- name: install general pip dependencies for Ansible
  pip:
    name: "{{ general.dependencies.pip }}"
    state: present
