---
nvidia:
  apt:
    package: nvidia-docker2=2.* # known good with 2.0.3+docker18.09.1-1
    repo_filename: nvidia_github_io_nvidia_docker_ubuntu18_04_nvidia_docker.list
    repos:
      libnvidia_container: deb https://nvidia.github.io/libnvidia-container/ubuntu18.04/$(ARCH) /
      nvidia_container_runtime: deb https://nvidia.github.io/nvidia-container-runtime/ubuntu18.04/$(ARCH) /
      nvidia_docker: deb https://nvidia.github.io/nvidia-docker/ubuntu18.04/$(ARCH) /
    signing_key_url: https://nvidia.github.io/nvidia-docker/gpgkey
