---
# Nvidia Docker Runtime Installation
- name: get the NVIDIA signing key
  apt_key:
    state: present
    url: "{{ nvidia.apt.signing_key_url }}"

- name: add the libnvidia-container repo
  apt_repository:
    filename: "{{ nvidia.apt.repo_filename }}"
    repo: "{{ nvidia.apt.repos.libnvidia_container }}"
    state: present

- name: add the nvidia-container-runtime repo
  apt_repository:
    filename: "{{ nvidia.apt.repo_filename }}"
    repo: "{{ nvidia.apt.repos.nvidia_container_runtime }}"
    state: present

- name: add the nvidia-docker repo
  apt_repository:
    filename: "{{ nvidia.apt.repo_filename }}"
    repo: "{{ nvidia.apt.repos.nvidia_docker }}"
    state: present

- name: install the nvidia-docker2 runtime
  apt:
    name: "{{ nvidia.apt.package }}"
    state: present
    update_cache: yes
  notify: "reload the docker service"
