---
docker:
  apt:
    package: docker-ce
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    signing_key_url: https://download.docker.com/linux/ubuntu/gpg
  group_name: docker
  service_name: docker
