---
docker:
  apt:
    package: docker-ce
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    signing_key_url: https://download.docker.com/linux/ubuntu/gpg
  container_name: jupyter
  group_name: docker
  image:
    name: tensorflow/tensorflow
    tag: 1.12.0-gpu-py3
  published_ports:
    - 8888:8888
  service_name: docker
