---
# Cuda Driver Package Installation
- name: copy the CUDA repo onto the machine
  copy:
    src: "{{ cuda.apt.repo }}"
    dest: "{{ general.working_dir }}/{{ cuda.apt.repo }}"

- name: get the CUDA signing key
  apt_key:
    state: present
    url: "{{ cuda.apt.signing_key_url }}"

- name: add the CUDA repo
  apt:
    deb: "{{ general.working_dir }}/{{ cuda.apt.repo }}"
    state: present

- name: install the CUDA drivers
  apt:
    name: "{{ cuda.apt.package }}"
    update_cache: yes
  notify: "reboot the machine"
