---
# Jupyter Docker Setup
- name: pull the Tensorflow GPU image
  docker_image:
    name: "{{ jupyter.image.name }}"
    state: present
    tag: "{{ jupyter.image.tag }}"
  tags:
    - jupyter

- name: start the Jupyter container
  docker_container:
    auto_remove: yes
    debug: no
    detach: yes
    env:
      PASSWORD: "{{ secrets.jupyter_password }}"
    image: "{{ jupyter.image.name }}:{{ jupyter.image.tag }}"
    name: "{{ jupyter.container_name }}"
    published_ports: "{{ jupyter.published_ports }}"
    pull: no
    read_only: no
    restart_policy: "no"
    state: started
    volumes: "{{ jupyter.volumes }}"
  tags:
    - jupyter
