---
# Jupyter Docker Setup
- name: pull the Tensorflow GPU image
  docker_image:
    name: "{{ jupyter.image.name }}"
    state: present
    tag: "{{ jupyter.image.tag }}"
    source: pull
  tags:
    - jupyter

- name: Set password
  lineinfile:
    path: /etc/jupyter_notebook_config.py
    line: "c.NotebookApp.password = u'{{ secrets.password_hash }}'"
    create: yes
  tags:
    - jupyter

- name: start the Jupyter container
  docker_container:
    auto_remove: no
    debug: no
    detach: yes
    image: "{{ jupyter.image.name }}:{{ jupyter.image.tag }}"
    name: "{{ jupyter.container_name }}"
    published_ports: "{{ jupyter.published_ports }}"
    pull: no
    read_only: no
    restart_policy: always
    runtime: "{{ secrets.runtime }}"
    state: started
    volumes:
      - "{{ secrets.volumes.data }}"
      - "{{ secrets.volumes.source }}"
      - "/etc/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py"
  tags:
    - jupyter
