---
# Docker Package Installation
- name: add Docker's official GPG key
  apt_key:
    state: present
    url: "{{ docker.apt.signing_key_url }}"

- name: add Docker apt repository
  apt_repository:
    repo: "{{ docker.apt.repo }}"
    state: present

- name: install Docker CE
  apt:
    name: "{{ docker.apt.package }}"
    state: present
    update_cache: yes
