---
# General Docker Setup
- import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian' # debian, ubuntu

- name: ensure the docker service starts at boot
  systemd:
    name: "{{ docker.service_name }}"
    enabled: yes
    state: started

- name: create Docker group to avoid running as root
  group:
    name: "{{ docker.group_name }}"
    state: present

- name: add users to Docker group
  user:
    append: yes
    groups:
      - "{{ docker.group_name }}"
    name: "{{ item }}"
  loop: "{{ users }}"
